Repository ArthuryanLoheac/Jetpack, pull requests merged in 2025-04, with the labels that each got.

#30 :sparkles: hello command in server & client
  include/clientRun/ClientRun.hpp
  include/game/gameConstants.hpp
  main_client.cpp
  src/client/client/CommandHandling.cpp
  src/client/client/ConnectionClient.cpp
  src/client/client/DataManager.cpp
  src/client/client/DataManager.hpp
  src/client/graphic/BackGround.hpp
  src/client/graphic/Update.cpp
  src/server/client/Client.cpp
Labels: enhancement

#32 📝 Add the RFC documentation
  doc/RFC_Jetpack.txt
Labels: documentation

#34 :memo: Add new command MAP for client
  doc/RFC_Jetpack.txt
Labels: documentation

#35 :bug: Fix workflow to use the rule in the Makefile with the right flags
  .github/workflows/pain_au_chocolat.yml
Labels: bug

#37 :sparkles: add music to the game
  doc.txt
  include/clientRun/ClientRun.hpp
  src/client/graphic/GraphicalClient.cpp
  src/client/graphic/Update.cpp
  src/client/graphic/game/Game.cpp
  src/client/graphic/game/Game.hpp
  src/client/graphic/window/Window.cpp
  src/client/graphic/window/Window.hpp
  src/log/Log.hpp
Labels: enhancement

#38 :memo: Fix documentation to be more RFC-based
  doc.txt
Labels: documentation

#39 Position recup
  include/clientRun/ClientRun.hpp
  main_client.cpp
  src/client/client/Client.cpp
  src/client/client/Client.hpp
  src/client/client/ClientIO.cpp
  src/client/client/CommandHandling.cpp
  src/client/client/ConnectionClient.cpp
  src/server/client/Client.cpp
  src/server/client/ClientServer.cpp
  src/server/client/ClientServer.hpp
  src/server/client/ClientServerIO.cpp
  src/server/server/Server.hpp
Labels: enhancement

#40 :sparkles: Add sending START and receiving READY and MAP on the server
  src/server/client/ClientServer.hpp
  src/server/commands/Commands.cpp
  src/server/commands/Commands.hpp
  src/server/commands/receiveCommands.cpp
  src/server/gameSimulation/GameSimulation.cpp
  src/server/gameSimulation/GameSimulation.hpp
  src/server/server/Server.cpp
  src/server/server/Server.hpp
Labels: enhancement

#41 :sparkles: simule les positions des joueurs
  Makefile
  include/clientRun/ClientRun.hpp
  include/game/gameConstants.hpp
  main_client.cpp
  src/client/client/Client.cpp
  src/client/client/CommandHandling.cpp
  src/client/client/ConnectionClient.cpp
  src/client/client/DataManager.cpp
  src/client/client/DataManager.hpp
  src/client/graphic/GraphicalClient.cpp
  src/client/graphic/ImageClass.hpp
  src/client/graphic/Player.hpp
  src/server/client/ClientServer.cpp
  src/server/client/ClientServer.hpp
  src/server/client/ClientServerIO.cpp
  src/server/gameSimulation/GameSimulation.cpp
  src/server/gameSimulation/GameSimulation.hpp
  src/server/server/Server.cpp
  src/server/server/Server.hpp
  src/server/server/ServerGame.cpp
Labels: enhancement

#47 :bug: bug meme images pour chaque joueurs
  Makefile
  include/clientRun/ClientRun.hpp
  main_client.cpp
  src/client/client/CommandHandling.cpp
  src/client/client/DataManager.cpp
  src/client/client/DataManager.hpp
  src/client/graphic/BackGround.hpp
  src/client/graphic/GraphicalClient.cpp
  src/client/graphic/ImageClass.cpp
  src/client/graphic/ImageClass.hpp
  src/client/graphic/Player.hpp
  src/client/graphic/Update.cpp
  src/client/graphic/game/Game.cpp
Labels: bug

#51 :sparkles: simuler gravité et position en local
  include/clientRun/ClientRun.hpp
  main_client.cpp
  src/client/client/CommandHandling.cpp
  src/client/client/DataManager.cpp
  src/client/client/DataManager.hpp
  src/client/graphic/GraphicalClient.cpp
  src/client/graphic/Player.hpp
  src/client/graphic/Update.cpp
Labels: enhancement

#54 :sparkles: add Map checking
  src/server/client/ClientServer.cpp
  src/server/jetpackServer.cpp
  src/server/server/ServerGame.cpp
Labels: enhancement

#55 15 gestion de la collision avec les objets du monde
  src/server/Obstacle.cpp
  src/server/Obstacle.hpp
  src/server/client/ClientServer.hpp
  src/server/server/Server.cpp
  src/server/server/Server.hpp
  src/server/server/ServerGame.cpp
Labels: enhancement

#56 50 fix segfault when quitting game
  .gitignore
  doc.txt
  include/clientRun/ClientRun.hpp
  main_client.cpp
  src/client/client/ConnectionClient.cpp
  src/client/client/DataManager.cpp
  src/client/client/DataManager.hpp
  src/client/graphic/GraphicalClient.cpp
  src/server/client/ClientServerIO.cpp
  src/server/server/ServerGame.cpp
Labels: bug

#58 :sparkles: Implement handleDeath command and update Player class for alive status management
  src/client/client/CommandHandling.cpp
  src/client/graphic/Player.hpp
  src/server/server/ServerGame.cpp
Labels: enhancement

#64 :sparkles: Add drawTotalCoins function to display total coins on the screen
  src/client/graphic/UpdateGame.cpp
  src/client/graphic/game/Game.cpp
  src/client/graphic/game/Game.hpp
Labels: enhancement

#71 :sparkles: condition de victoires
  doc.txt
  src/client/graphic/Update.cpp
  src/server/client/ClientServer.hpp
  src/server/server/Server.cpp
  src/server/server/Server.hpp
  src/server/server/ServerGame.cpp
  tests/basic.map
Labels: enhancement

#70 🐛 Fix bug when the first player quit the game in the menu
  src/server/server/ServerMenu.cpp
Labels: bug

#75 🐛 Fix game not starting when having more than 2 players
  src/server/server/Server.cpp
  src/server/server/ServerGame.cpp
Labels: bug

#69 :sparkles: Add leaderboard functionality to display player scores
  src/client/graphic/game/Game.cpp
  src/client/graphic/game/Game.hpp
Labels: enhancement

#77 :bug: Faire que les commandes renvoies OK ou KO
  src/server/client/ClientServerIO.cpp
Labels: enhancement

#78 :sparkles: Message disconnect
  Makefile
  src/client/client/CommandHandling.cpp
  src/client/graphic/Player.cpp
  src/client/graphic/Player.hpp
  src/client/graphic/UpdateGame.cpp
Labels: enhancement

#80 :sparkles: Add player name display and adjust leaderboard transparency
  Makefile
  src/client/graphic/Player.cpp
  src/client/graphic/Player.hpp
  src/client/graphic/UpdateGame.cpp
  src/client/graphic/game/Game.cpp
  src/server/server/ServerMenu.cpp
Labels: enhancement
